import { spawnSync } from "node:child_process";
import {
  chmodSync,
  cpSync,
  existsSync,
  mkdirSync,
  rmSync,
  writeFileSync
} from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const functionName = "community-map-api";
const stageRoot = join(repoRoot, "apps/api/.cloudbase");
const functionDir = join(stageRoot, functionName);

const copyDir = (source, target) => {
  cpSync(source, target, {
    recursive: true,
    filter: (path) =>
      !path.includes("/node_modules/") &&
      !path.endsWith(".tsbuildinfo") &&
      !path.endsWith(".DS_Store")
  });
};

const resolveEsbuildBin = () => {
  const candidates = [
    join(repoRoot, "apps/api/node_modules/.bin/esbuild"),
    join(repoRoot, "node_modules/.bin/esbuild"),
    join(repoRoot, "node_modules/.pnpm/node_modules/.bin/esbuild")
  ];
  const esbuildBin = candidates.find((candidate) => existsSync(candidate));

  if (!esbuildBin) {
    throw new Error(
      "Could not find esbuild. Run pnpm install before preparing the CloudBase function."
    );
  }

  return esbuildBin;
};

rmSync(functionDir, { force: true, recursive: true });
mkdirSync(functionDir, { recursive: true });

copyDir(join(repoRoot, "apps/api/src"), join(functionDir, "src"));
copyDir(join(repoRoot, "packages/shared/src"), join(functionDir, "shared/src"));

writeFileSync(
  join(functionDir, "shared/package.json"),
  `${JSON.stringify(
    {
      name: "@community-map/shared",
      version: "0.1.0",
      private: true,
      type: "module",
      exports: {
        ".": "./src/index.ts"
      },
      dependencies: {
        zod: "^3.24.2"
      }
    },
    null,
    2
  )}\n`
);

const esbuild = spawnSync(
  resolveEsbuildBin(),
  [
    "apps/api/src/http-function.ts",
    "--bundle",
    "--platform=node",
    "--target=node18",
    "--format=cjs",
    "--alias:@community-map/shared=./packages/shared/src/index.ts",
    `--outfile=${join(functionDir, "index.cjs")}`
  ],
  {
    cwd: repoRoot,
    stdio: "inherit"
  }
);

if (esbuild.status !== 0) {
  throw new Error(`esbuild failed with exit code ${esbuild.status ?? "unknown"}`);
}

writeFileSync(
  join(functionDir, "package.json"),
  `${JSON.stringify(
    {
      name: "community-map-api",
      version: "0.1.0",
      private: true,
      scripts: {
        start: "node index.cjs"
      }
    },
    null,
    2
  )}\n`
);

const bootstrap = join(functionDir, "scf_bootstrap");
writeFileSync(
  bootstrap,
  [
    "#!/bin/bash",
    "set -e",
    "export PORT=${PORT:-9000}",
    "/var/lang/node18/bin/node index.cjs",
    ""
  ].join("\n")
);
chmodSync(bootstrap, 0o755);

writeFileSync(
  join(functionDir, "README.md"),
  [
    "# community-map-api CloudBase HTTP function",
    "",
    "Generated by `pnpm --filter @community-map/api build:cloudbase-http`.",
    "",
    "Deploy with CloudBase MCP using:",
    "",
    "```text",
    `manageFunctions(action="createFunction", functionRootPath="${stageRoot}", func={name:"${functionName}", type:"HTTP", protocolType:"HTTP", runtime:"Nodejs18.15", timeout:30, envVariables:{API_PROVIDER:"cloudbase", CLOUDBASE_PROVIDER_MODE:"live", CLOUDBASE_ENV_ID:"cloud1-d7gxdk8t43bd639c0"}})`,
    "```",
    "",
    "The function starts self-contained bundled `index.cjs` through `scf_bootstrap`, listens on port 9000, and reuses the canonical Koa `createApp()` route set.",
    "No runtime dependency install step is required before upload. `src/` and `shared/` are included for source provenance only.",
    ""
  ].join("\n")
);

console.log(`Prepared ${functionName} at ${relative(repoRoot, functionDir)}`);
